/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ptg.util.around;

public class around {
  public static SWIGTYPE_p_double new_double_array(int nelements) {
    long cPtr = aroundJNI.new_double_array(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static void delete_double_array(SWIGTYPE_p_double ary) {
    aroundJNI.delete_double_array(SWIGTYPE_p_double.getCPtr(ary));
  }

  public static double double_array_getitem(SWIGTYPE_p_double ary, int index) {
    return aroundJNI.double_array_getitem(SWIGTYPE_p_double.getCPtr(ary), index);
  }

  public static void double_array_setitem(SWIGTYPE_p_double ary, int index, double value) {
    aroundJNI.double_array_setitem(SWIGTYPE_p_double.getCPtr(ary), index, value);
  }

  public static void inito() {
    aroundJNI.inito();
  }

  public static void initp() {
    aroundJNI.initp();
  }

  public static void finish() {
    aroundJNI.finish();
  }

  public static void outputInstanceToSVG(SWIGTYPE_p_std__string fname) {
    aroundJNI.outputInstanceToSVG(SWIGTYPE_p_std__string.getCPtr(fname));
  }

  public static void addRect(double x1, double y1, double x2, double y2) {
    aroundJNI.addRect(x1, y1, x2, y2);
  }

  public static SWIGTYPE_p_double getPath(int x1, int y1, int x2, int y2) {
    long cPtr = aroundJNI.getPath(x1, y1, x2, y2);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static void freePath(SWIGTYPE_p_double ar) {
    aroundJNI.freePath(SWIGTYPE_p_double.getCPtr(ar));
  }

}
