/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ptg.util.around;

class aroundJNI {
  public final static native long new_double_array(int jarg1);
  public final static native void delete_double_array(long jarg1);
  public final static native double double_array_getitem(long jarg1, int jarg2);
  public final static native void double_array_setitem(long jarg1, int jarg2, double jarg3);
  public final static native void inito();
  public final static native void initp();
  public final static native void finish();
  public final static native void outputInstanceToSVG(long jarg1);
  public final static native void addRect(double jarg1, double jarg2, double jarg3, double jarg4);
  public final static native long getPath(int jarg1, int jarg2, int jarg3, int jarg4);
  public final static native void freePath(long jarg1);
}
